
### PARAMETERS ###

Parameters:
  InstanceType:
    Description: TR7 ASP host EC2 Instance type.
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: Must be a valid EC2 instance type.

  SecurityGroupDescription:
    Description: Description for the Security Group attached to TR7 ASP.
    Type: String
  
  SecurityGroupPort:
    Description: Port number of the Security Group that will be attached to TR7 ASP.
    Type: Number
    MinValue: 1150
    MaxValue: 65535

  KeyName:
    Description: Key pair to enable SSH access to TR7 ASP.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: The provided name must be an existing EC2 KeyPair.

  SecurityGroupIngressCIDR:
    Description: IP address range for communication with TR7 ASP.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: IP Address must be in the form d.d.d.d/d

  ASPVPC:
    Description: VPC for TR7 ASP to operate in.
    Type: AWS::EC2::VPC::Id

  ASPSubnetIDs:
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"

  ASPSubnetIPBlocks:
    Description: "Three CIDR blocks seperated by comma"
    Type: CommaDelimitedList
    Default: "10.0.48.0/24, 10.0.112.0/24, 10.0.176.0/24"

### RESOURCES ###

Resources:
  ASPEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0742b4e673072066f
      SubnetId: !Ref DbSubnet1

  ASPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
          IpProtocol: tcp
      VpcId: !Ref ASPVPC

  DbSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ASPVPC
      CidrBlock: !Select [0, !Ref ASPSubnetIPBlocks]

  DbSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ASPVPC
      CidrBlock: !Select [1, !Ref ASPSubnetIPBlocks]

  DbSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ASPVPC
      CidrBlock: !Select [2, !Ref ASPSubnetIPBlocks]

